FROM nginx:latest

RUN apt-get update && apt-get install -y openssl


RUN mkdir -p /etc/nginx/ssl


RUN openssl req -new -newkey rsa:2048 -days 365 -nodes -x509 \
    -subj "/C=RU/ST=Moscow/L=Moscow/O=makara/CN=localhost" \
    -keyout /etc/nginx/ssl/server.key \
    -out /etc/nginx/ssl/server.crt


COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
